// BASE DE DATOS COMPLETA: LOS 31 PRODUCTOS
const database = {
    "productos": [
        { "id": "FORZA_VITA_PREMIUM", "nombre": "Forza Vita Premium", "pres": "600g", "precio": 240, "ing": ["Habas", "Sacha Inchi", "Chía", "Plátano", "Cañihua", "Maca", "Avena", "Quinua", "Linaza", "Girasol"], "desc": "Aumenta energía, fortalece sistema inmune y apetito. Mejora triglicéridos y colesterol. Antiinflamatorio.", "tags": ["anemia", "cansancio", "apetito", "energía", "corazón"] },
        { "id": "NEO_VITA_GOLD", "nombre": "Neo Vita Gold", "pres": "300g", "precio": 180, "ing": ["Arándano", "Maíz Morado", "Uva", "Fresa", "Guanábana", "Camu Camu", "Amalaki", "Hoja de Uva", "Hoja de Olivo", "Granada"], "desc": "Protección cardiovascular y renal. Antioxidante. Útil en varices, menopausia e infecciones urinarias.", "tags": ["riñones", "antioxidante", "varices", "menopausia", "presión", "circulación"] },
        { "id": "VIGOR_DETOX_GOLD", "nombre": "Vigor Detox Gold", "pres": "300g", "precio": 180, "ing": ["Tamarindo", "Piña", "Pitahaya", "Penca Tuna", "Manayupa", "Achicoria", "Muña", "Diente León", "Boldo", "Hinojo", "Probióticos"], "desc": "Digestión ligera. Elimina toxinas, mejora tránsito intestinal y flora. Ayuda en control de peso y ansiedad.", "tags": ["estreñimiento", "gases", "cólicos", "limpieza colon", "peso", "hígado"] },
        { "id": "ALOE_DIVINO_GOLD", "nombre": "Aloe Divino Gold", "pres": "300g", "precio": 180, "ing": ["Aloe Vera", "Penca Tuna", "Arándano", "Glutamina", "Menta", "Muña", "Yacón", "Cúrcuma", "Jengibre"], "desc": "Salud digestiva. Cicatrizante gástrico, alivia acidez y reflujo. Protege mucosa intestinal y hepática.", "tags": ["gastritis", "acidez", "reflujo", "úlceras", "estómago", "hígado"] },
        { "id": "BETA_GREEN_GOLD", "nombre": "Beta Green Gold", "pres": "300g", "precio": 180, "ing": ["Alcachofa", "Brócoli", "Espinaca", "Cardo Mariano", "Diente León", "Boldo", "Chlorella", "Espirulina", "Clorofila"], "desc": "Protección hepática. Desintoxicante biliar, purifica sangre, mejora defensas y salud tiroidea.", "tags": ["hígado graso", "manchas piel", "intoxicación", "tiroides", "digestión"] },
        { "id": "FACTOR_DEFENSE_GOLD", "nombre": "Factor Defense Gold", "pres": "300g", "precio": 180, "ing": ["Algarrobina", "Maca", "Noni", "Camu Camu", "Chanca Piedra", "Hoja Coca", "Moringa", "Ganoderma", "Uña de Gato"], "desc": "Defensa natural. Acción antiviral y antiinflamatoria. Protege riñones, alivia fatiga y estrés.", "tags": ["defensas", "virus", "inflamación", "riñones", "estrés", "articulaciones"] },
        { "id": "GLUTACELL_Q10", "pres": "600g", "nombre": "Glutacell Q10", "precio": 400, "ing": ["Calostro", "Coenzima Q10", "Ácido Hialurónico", "NRF2", "Células Madres", "L-Glutatión", "HMB", "BCAAs"], "desc": "Regenerador celular máximo. Fortalece inmunidad, regenera tejidos, mejora piel y masa muscular.", "tags": ["vejez", "inmunidad", "recuperación", "arrugas", "células"] },
        { "id": "FACTOR_DBT2", "nombre": "Factor DBT2", "pres": "300g", "precio": 180, "ing": ["Pasuchaca", "Canela", "Yacón", "Penca Tuna", "Graviola", "Moringa"], "desc": "Equilibrio de azúcar. Mejora sensibilidad a insulina, protege nervios y función del páncreas.", "tags": ["diabetes", "azúcar", "insulina", "glucosa"] },
        { "id": "MG8", "nombre": "Magnesio 8 en 1 (MG8)", "pres": "300g", "precio": 180, "ing": ["Citrato", "Bisglicinato", "Treonato", "Taurato", "Malato", "Quelado", "Cloruro", "Sulfato"], "desc": "Salud integral. Alivia ansiedad, calambres, mejora sueño, memoria, salud cardiaca y muscular.", "tags": ["calambres", "insomnio", "ansiedad", "estrés", "memoria", "corazón"] },
        { "id": "NVT_ENERGY_GOLD", "nombre": "NVT Energy Gold", "pres": "300g", "precio": 180, "ing": ["Maca", "Ginseng", "Arándano", "Maíz Morado", "Coco"], "desc": "Revitalizante. Mejora rendimiento físico, estado de ánimo y función pulmonar.", "tags": ["fatiga", "energía", "libido", "estudio"] },
        { "id": "SETA_VITAL", "nombre": "Seta Vital (10 en 1)", "pres": "300g", "precio": 200, "ing": ["Cordyceps", "Ganoderma", "Shiitake", "Maitake", "Melena León", "Poria", "Chaga", "Wood Ear"], "desc": "Defensa Total. Inmunomodulador, bienestar mental, protege contra estrés oxidativo.", "tags": ["cáncer", "defensas altas", "cerebro", "inmunidad"] },
        { "id": "FACTOR_SLEEP_GOLD", "nombre": "Factor Sleep Gold", "pres": "300g", "precio": 180, "ing": ["Hierba Luisa", "Manzanilla", "Pimpinela", "Salvia", "Romero", "Naranja", "Limón"], "desc": "Relajante profundo. Calma ansiedad, estrés, ayuda en insomnio y fatiga muscular.", "tags": ["dormir", "insomnio", "ansiedad", "estrés"] },
        { "id": "FACTOR_PROST_GOLD", "nombre": "Factor PROST Gold", "pres": "300g", "precio": 180, "ing": ["Maca", "Achiote", "Mashua", "Calabaza", "Uña de Gato", "Jengibre", "Cúrcuma"], "desc": "Salud masculina. Desintoxicante renal, previene inflamación prostática, aporta vigor.", "tags": ["próstata", "riñones", "urinario", "libido"] },
        { "id": "FACTOR_V1ST4", "nombre": "Factor V1ST4", "pres": "300g", "precio": 180, "ing": ["Zanahoria", "Luteína", "Astaxantina", "Uva", "Moringa"], "desc": "Salud ocular. Protege retina, previene degeneración macular y mejora agudeza visual.", "tags": ["vista", "ojo seco", "cataratas"] },
        { "id": "FACTOR_NEUMN", "nombre": "Factor NEUMN", "pres": "300g", "precio": 180, "ing": ["Pulmonaria", "Eucalipto", "Propóleo", "Equinácea", "Asmachilca", "Totumo"], "desc": "Salud respiratoria. Alivia tos, expectorante, antibiótico natural pulmonar.", "tags": ["tos", "asma", "pulmones", "gripe"] },
        { "id": "CLG_BIO_MUJER", "nombre": "CLG-BIO Mujer", "pres": "300g", "precio": 200, "ing": ["Colágeno", "Ácido Hialurónico", "Fenogreco", "Acaí", "L-Cisteína"], "desc": "Belleza y hormonas. Mejora piel, cabello, uñas y regula ciclo menstrual.", "tags": ["piel", "menopausia", "cabello", "hormonas"] },
        { "id": "CLG_BIO_HOMBRE", "nombre": "CLG-BIO Hombre", "pres": "300g", "precio": 200, "ing": ["Colágeno", "Huanarpo Macho", "L-Carnitina", "Condroitina", "Lucraco"], "desc": "Vigor y articulaciones. Recuperación muscular y potencia sexual masculina.", "tags": ["libido", "músculos", "articulaciones"] },
        { "id": "CAPS_CURCUMA", "nombre": "Cápsulas Cúrcuma", "pres": "100 cap", "precio": 160, "ing": ["Cúrcuma pura"], "desc": "Antiinflamatorio y digestivo. Mejora problemas de articulaciones y alergias.", "tags": ["dolor", "artritis", "inflamación"] },
        { "id": "CAPS_CANELA", "nombre": "Cápsulas Canela", "pres": "100 cap", "precio": 160, "ing": ["Canela pura"], "desc": "Control glucémico. Regula colesterol y mejora indigestión.", "tags": ["azúcar", "colesterol", "triglicéridos"] },
        { "id": "FACTOR_CRZ4", "nombre": "Factor CRZ4", "pres": "300g", "precio": 180, "ing": ["Resveratrol", "Omega 3", "CoQ10", "Maíz Morado"], "desc": "Salud cardiaca. Regula presión arterial y protege el corazón.", "tags": ["corazón", "hipertensión", "presión"] },
        { "id": "CAPS_JENGIBRE", "nombre": "Cápsulas Jengibre", "pres": "100 cap", "precio": 160, "ing": ["Jengibre Puro"], "desc": "Antiinflamatorio. Mejora náuseas, boca seca y calma dolores articulares.", "tags": ["náuseas", "dolor", "articulaciones"] },
        { "id": "CLG_BIO", "nombre": "CLG-BIO", "pres": "300g", "precio": 180, "ing": ["Colágeno Hidrolizado", "Maracuyá", "Camu Camu", "Cúrcuma", "Ginseng"], "desc": "Salud articular básica y regenerador óseo.", "tags": ["articulaciones", "huesos", "piel"] },
        { "id": "FACTOR_F1TT", "nombre": "Factor F1TT", "pres": "300g", "precio": 200, "ing": ["Té Verde", "Té Negro", "Matcha", "Garcinia Cambogia", "L-Carnitina"], "desc": "Control de peso, acelera el metabolismo y quema grasa.", "tags": ["peso", "grasa", "metabolismo"] },
        { "id": "FACTOR_L3GS", "nombre": "Factor L3GS", "pres": "300g", "precio": 180, "ing": ["Castaño de India", "Ruscus", "Caléndula", "Ciprés"], "desc": "Circulación y várices. Mejora retorno venoso y alivia piernas cansadas.", "tags": ["várices", "circulación", "piernas"] },
        { "id": "FACTOR_PKE_AOX", "nombre": "Factor PKE AOX", "pres": "300g", "precio": 180, "ing": ["Acaí", "Arándano Azul", "DHA", "Omega 3", "Aceite de Coco"], "desc": "Energía infantil. Promueve desarrollo cerebral y protege salud ocular.", "tags": ["niños", "cerebro", "energía"] },
        { "id": "FACTOR_PKE_FORTE", "nombre": "Factor PKE Forte", "pres": "300g", "precio": 180, "ing": ["Kiwicha", "Cañihua", "Quinua", "Cacao", "DHA"], "desc": "Nutrición infantil. Fortalece huesos y sistema inmune de los niños.", "tags": ["crecimiento", "niños", "huesos"] },
        { "id": "FACTOR_Q4ALM", "nombre": "Factor Q4ALM", "pres": "300g", "precio": 180, "ing": ["Dong Quai", "Aguaje", "Yohimbina", "L-Arginina", "Fenogreco"], "desc": "Salud femenina. Regula ciclo menstrual y alivia síntomas de menopausia.", "tags": ["menopausia", "hormonas", "femenina"] },
        { "id": "FACTOR_R3TUM", "nombre": "Factor R3TUM", "pres": "300g", "precio": 180, "ing": ["Sangre de Grado", "Copaiba", "Ginkgo Biloba", "Aloe Vera"], "desc": "Bienestar interior. Cicatrizante rectal, disminuye hemorroides.", "tags": ["hemorroides", "fisuras", "inflamación"] },
        { "id": "FACTOR_RVU", "nombre": "Factor RVU", "pres": "300g", "precio": 180, "ing": ["Arándano Rojo", "D-Manosa", "Chanca Piedra", "Cola de Caballo"], "desc": "Vías urinarias. Previene infecciones y ayuda a disolver cálculos renales.", "tags": ["infección urinaria", "riñones", "cálculos"] },
        { "id": "FACTOR_THYRD", "nombre": "Factor THYRD", "pres": "300g", "precio": 180, "ing": ["Lactobacillus", "L-Triptófano", "L-Glutatión", "NAC"], "desc": "Tiroides. Regula metabolismo, reduce fatiga y protege daño oxidativo.", "tags": ["tiroides", "metabolismo", "fatiga"] },
        { "id": "MORGANO", "nombre": "Morgano Café", "pres": "200g", "precio": 180, "ing": ["Café Liofilizado", "Ganoderma", "Moringa", "Uña de Gato"], "desc": "Café nutritivo. Antienvejecimiento, energía y antioxidante.", "tags": ["energía", "café", "antioxidante"] }
    ],
    "packs": [
        { "n": "Pack Digestivo", "o": 390, "r": 540, "ids": ["ALOE_DIVINO_GOLD", "BETA_GREEN_GOLD", "VIGOR_DETOX_GOLD"], "d": "Saneamiento total del sistema digestivo e hígado." },
        { "n": "Pack Inmunológico Básico", "o": 440, "r": 600, "ids": ["FORZA_VITA_PREMIUM", "FACTOR_DEFENSE_GOLD", "NEO_VITA_GOLD"], "d": "Refuerzo esencial de defensas y energía." },
        { "n": "Pack Inmunológico Pro", "o": 560, "r": 760, "ids": ["GLUTACELL_Q10", "FACTOR_DEFENSE_GOLD", "NEO_VITA_GOLD"], "d": "Regeneración celular y alta protección inmune." },
        { "n": "Pack Inmunológico Full", "o": 740, "r": 1000, "ids": ["GLUTACELL_Q10", "FORZA_VITA_PREMIUM", "FACTOR_DEFENSE_GOLD", "NEO_VITA_GOLD"], "d": "Máxima protección, energía y recuperación total." }
    ]
};
